email_archiviste = "benjaminlafleur86@gmail.com"
mdp_archiviste = "nyxx lbdq lbod xecx"
NOTION_TOKEN = "secret_ntn_280600344753FGJQBKVFuHXpRPEHztu9vNu6e6ixKozdHe"
NOTION_DATABASE_ID = "17a6888225ab8000882adcfc2082fd47"
