email_archiviste = "benjaminlafleur86@gmail.com"
mdp_archiviste = "nyxx lbdq lbod xecx"
NOTION_TOKEN = "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"
NOTION_DATABASE_ID = "17a6888225ab8000882adcfc2082fd47"
